name: neural_tts
description: On-device neural TTS engine for Flutter. Supports Kitten, Kokoro, Supertonic, and System OS TTS via native ONNX Runtime.
version: 0.4.1
repository: https://github.com/abdulmominsakib/neural_tts
homepage: https://github.com/abdulmominsakib/neural_tts

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  path_provider: ^2.1.5
  archive: ^4.0.9
  dio: ^5.9.2
  espeak: ^0.1.3
  flutter_onnxruntime: ^1.6.0
  audioplayers: ^6.6.0
  phonemize: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.localmind.neural_tts
        pluginClass: NeuralTtsPlugin
